# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: before Free up disk space
        run: |
          df -h
          
      - name: list installed software
        run: |
          apt list --installed
          
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc
          docker rmi $(docker images -q) || true
           # 移除其他不需要的软件包
          sudo apt-get purge -y \
          adoptium-ca-certificates \
          ant ant-optional \
          apache2* \
          aria2 \
          azure-cli \
          bison \
          buildah \
          byobu \
          clang-* \
          cloud-init \
          cpp-12 cpp-13 \
          firebird* \
          firefox \
          flex \
          g\+\+-12 g\+\+-13 \
          gfortran* \
          gh \
          ghc* \
          git-ftp \
          google-chrome-stable \
          google-cloud-cli* \
          haveged \
          htop \
          imagemagick* \
          kubectl \
          libaom* libavahi* libavif* libgdk* libgtk* libheif* libjbig* libjpeg* liblcms* liblerc* liblqr* libmng* libmspack* libopenjp2* libpng* libraw* librsvg* libtiff* libwebp* \
          libasound* \
          libclang* \
          libllvm* \
          libmysqlclient* \
          libpq* \
          libruby* \
          libvulkan* \
          libx11* libxau* libxcb* libxcomposite* libxcursor* libxdamage* libxdmcp* libxext* libxfixes* libxfont* libxft* libxi* libxinerama* libxkb* libxml2* libxmu* libxpm* libxrandr* libxrender* libxss* libxt* libxtst* libxxf86vm* \
          lld-* \
          llvm-* \
          mercurial* \
          microsoft-edge-stable \
          mlock \
          modemmanager \
          mysql-* \
          nginx* \
          php* \
          podman \
          pollinate \
          postgresql-* \
          powershell \
          rake \
          ruby* \
          session-manager-plugin \
          skopeo \
          snapd \
          snmp \
          sosreport \
          sphinxsearch \
          swig \
          sysstat \
          temurin-11-jdk temurin-17-jdk temurin-8-jdk temurin-25-jdk \
          tex-common texinfo \
          tmux \
          tree \
          ufw \
          upx-ucl \
          vim \
          walinuxagent \
          x11-common xauth xdg-user-dirs xdg-utils xvfb \
          zsync && \
          sudo apt-get autoremove -y && \
          sudo apt-get clean


      - name: after Free up disk space
        run: |
          df -h
